### ISSUE TITLE
Usage question: single entry for source or per sampling?

### ISSUE THREAD

**Issue by BloodyRain2k** [gregmalcolm/ed-materializer#18]
I've reached a point with my own client for the api where I can not only patch system coords (fetched from the netLogs) but also add systems and bodies and supply data.
Now here's the question, I went past only supplying BINARY data and made it possible to add specific source data, but I've messed up and just added 4 MM's to the Meso entry for a body.
Luckily the sample set is at this point so big because I still didn't find the Very Rare that it doesn't matter much, but it'd be easily fixable if it were not one big entry. Might need to add local logging, mhm.

Which is the question: is one entry per type (Meso, MM, Chon, Oc1, Oc2) prefered or would it be okay to supply each sampling with a seperate entry?
I already know that the front-end's overview would be spammed to hell if I were to go for the latter but that'd be fixable. (not by me though, can't Ruby for the hell of it...)

**Comment by gregmalcolm** [comment]
Yeah, one resource type per per survey is definitely preferable. Obviously I haven't validated against it but when I get around to supporting it in the web front end I'll be making it one resource type per survey there. I wouldn't worry about it too much if it's a one off mistake, but you can always delete survey entries through the api if you wanted to consolidate.

**Comment by BloodyRain2k** [comment]
Eh, little misunderstanding here, I didn't mean source specific survey vs BINARY, I meant multiple surveys per source vs one survey for the total of said resource.
Like submitting a chon survey of 2 iron and 1 nickel and another survey for another chon that dropped 1 sulphur and 1 phosphor vs a summary survey for chon's that would be 2 iron 1 nickel 1 sulphur 1 phosphor.

**Comment by gregmalcolm** [comment]
I think the only reason you'do get multiple chon surveys on a planet ordinarily is because they were performed by different people or on different dates.

So I might go survey europa, I might create an MM, an outcrop 1 and a chon giving me personally 3 survey records. But there might be multiple chons because someone else has also surveyed europa in a similar manner.

**Comment by BloodyRain2k** [comment]
That's what I meant, would it be prefered to have as few survey entries 
as possible as in one per commander per source like this one 
http://edmaterializer.com/surveying/surveys/5721 which is a summary of 
probably over 30 Mesos, or would it be (after adjusting the frontend to 
group them itself per commander) if I had made one survey entry per Meso 
drop?

The whole point about this was my little mess up where I added 3-4 MMs 
to the Meso drop summary, if they would've been seperated survey per 
drop then I could have just changed the type but since they were 
total'ed together and I didn't know anymore what they dropped could I 
not revert the numbers.

With the current way the frontend handles surveys would a per drop 
surveys be extremely messy but I think it'd be relatively easy to make 
it group them per commander together so that if I had seperated the Meso 
surveys into 30 per drop ones it could fetch them all and then just 
display the total as one summary entry.
Or even just group them by source in the way that it just shows "Meso on 
this planet have the following drop chances" and then just lists the 
totals across all commanders.

I'd prefer a per drop survey submission because that allows to easily 
correct the source type for example, but I don't wanna mess up the 
database either which is why I went with summarys for now.
Most ideal would be though if FD would just add these events to the logs 
and we'd just read that out, less mess up chance <.< but they don't like 
efficiency.

**Comment by gregmalcolm** [comment]
When I get around to doing these "scientific surveys" in the EDM frontend my plan is to show a kind of table of checkbox/number options, with the horizontal being resource type, and the vertical being the material type. So basically 6 rows. I'm going to make it look like one big survey, using a shared basecamp record.

The basecamp thing probably sounds a little wierd, but when I get around to the V5 interface I'm planning on renaming basecamps and surveys to survey_sheets and survey_items. But don't worry too much about that because I don't seem to be getting around to it that quickly and the existing data will still be there.
